### PR TITLE
retrieve data for entire postcode

### PR DESCRIPTION
**Pull request by richardbeare**
A simple function that returns address and coordinate data for entire postcodes. This is handy when generating random addresses within postcodes.

Apologies if I've failed to follow naming schemes, etc. Let me know if you want changes.

### CODE REVIEW

**Comment by HughParsonage** [comment]
Thank you! Only thing I'd prefer is the name -- `fetch_postcodes` rather than `fetchpostcodes` and to add a test (perhaps that when a particular postcode is fetched an address will appear?).

Also, unless you object, please add yourself as an author to the DESCRIPTION file.

**Comment by richardbeare** [comment]
Will do. I'll amend the commit and do a force push tonight.

**Comment by richardbeare** [comment]
A query - my test plan was to run a postcode query, sample per postcode, as in the example, then geocode the resulting addresses and compare the lat/lon from the postcode result to the geocode result. However they are slightly different (by varying magnitudes). My impression was that each address had an associated lat/lon in the database. I am passing the results as follows:

```r
with(postcodequeryresult,
    geocode(flat_number = FLAT_NUMBER,
            number_first = NUMBER_FIRST,
            building_name = BUILDING_NAME,
            street_name = STREET_NAME,
            street_type = STREET_TYPE_CODE,
            postcode = POSTCODE))
```
Errors can be like this
``` r
[3] -27.5 - -27.5 == -1.17e-04
```
May be mostly to do with flat numbers - is there some interpolation happening. If so, is there a magnitude of error I should allow?

**Comment by HughParsonage** [comment]
The answer is "there shouldn't be" but the package is still quite nascent, so I'm not sure whether this is a limitation of the PSMA data or the addresses or the package logic. Could you provide a reproducible example though (with `set.seed` if you're sampling)?

**Comment by richardbeare** [comment]
Messy version - testing whether NAs were causing the problem

```r
test_that("Random samples match the geocode", {
  pcodes <- c(4171, 4032, 4122)
  bnedata <- fetch_postcodes(pcodes)
  set.seed(89)
  three.per.postcode <- bnedata[, .SD[sample(.N, 3)], by=.(POSTCODE)]
  coordinates <- lapply(1:nrow(three.per.postcode), function(idx) {
    if (is.na(three.per.postcode$FLAT_NUMBER[idx])) {
      geocode(number_first = three.per.postcode$NUMBER_FIRST[idx],
              street_name = three.per.postcode$STREET_NAME[idx],
              street_type = three.per.postcode$STREET_TYPE_CODE[idx],
              postcode = three.per.postcode$POSTCODE[idx])
    } else {
      geocode(flat_number = three.per.postcode$FLAT_NUMBER[idx],
              number_first = three.per.postcode$NUMBER_FIRST[idx],
              street_name = three.per.postcode$STREET_NAME[idx],
              street_type = three.per.postcode$STREET_TYPE_CODE[idx],
              postcode = three.per.postcode$POSTCODE[idx])
    }
    }
  )
  coordinates <- do.call(rbind, coordinates)
  print(three.per.postcode)
  print(coordinates)
  expect_equal(coordinates$LATITUDE, three.per.postcode$LATITUDE)
  expect_equal(coordinates$LONGITUDE, three.per.postcode$LONGITUDE)
```

**Comment by richardbeare** [comment]
OK, I've added a test that includes the failures mentioned above. I think it ought to work. Will begin to investigate in more detail now that the fetch_postcode stuff in all in the branch.

**Pull request merged**
